# Generated by Django 5.1.4 on 2024-12-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
